# Generated by Django 3.2.3 on 2021-05-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
