# Generated by Django 3.2.3 on 2021-05-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
