# Generated by Django 3.2.3 on 2021-05-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20210521_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
