# Generated by Django 3.2.3 on 2021-05-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='id',
            new_name='sno',
        ),
    ]
