# Generated by Django 3.2.3 on 2021-05-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_rename_id_blogcomment_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='timestamp',
        ),
    ]
