# Generated by Django 3.2.3 on 2021-05-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_remove_blogcomment_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
