# Generated by Django 3.2.3 on 2021-05-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20210521_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogAppComment',
        ),
    ]
