# Generated by Django 3.2.3 on 2021-12-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trending',
            field=models.CharField(choices=[('trending', 'Trending'), ('not trending', 'Not Trending')], default='not trending', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_category',
            field=models.CharField(choices=[('general', 'General'), ('tect', 'Tech'), ('food', 'Food'), ('travel', 'Travel'), ('sports', 'Sports')], default='general', max_length=50),
        ),
    ]
