# Generated by Django 3.2.3 on 2021-12-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20211228_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='trending',
            field=models.CharField(choices=[('trending', 'Trending'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
