# Generated by Django 3.2.3 on 2021-12-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_alter_post_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_category',
            field=models.CharField(choices=[('general', 'General'), ('tech', 'Tech'), ('food', 'Food'), ('travel', 'Travel'), ('sports', 'Sports')], default='general', max_length=50),
        ),
    ]
