# Generated by Django 3.2.3 on 2021-12-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_auto_20211229_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='trending',
            field=models.CharField(choices=[('trending', 'Trending'), ('normal', 'Normal')], default='normal', max_length=50),
        ),
    ]
